name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (Python ${{ matrix.python-version }})
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - 3.10
          - 3.11
    steps:
    - name: Checkout SMB docker container
      run: docker pull pwntr/samba-alpine

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: python -m pip install -U pip wheel setuptools

    - name: Install local code
      run: python -m pip install -e .

    - name: Install Test dependencies
      run: python -m pip install -e ".[test]"

    - name: Test with coverage
      run: pytest -v --doctest-modules --junitxml=junit/test-results.xml --cov=miarec_ftpfs --cov-report=xml --cov-report=html tests/

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
